### ISSUE TITLE
The dependency of the scss loader is missing

### ISSUE THREAD

**Issue by DannyFeliz** [drewjbartlett/vue-switches#2]
Because you're ussing scss This component throws an exception if you use it in an application that does not have the scss loader

**Comment by drewjbartlett** [comment]
It's likely because node-sass is in the dev dependencies. I can move this tomorrow.

**Comment by drewjbartlett** [comment]
@DannyFeliz made this change https://github.com/drewjbartlett/vue-switches/commit/4346acaffc95555d390bdfd55417e3803677fde8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by DannyFeliz** [comment]
Thank you very much @drewjbartlett :fist_right:  :1st_place_medal:
