### ISSUE TITLE
Is the node-sass dependency necessary?

### ISSUE THREAD

**Issue by sellomkantjwa** [drewjbartlett/vue-switches#5]
I installed the library and ended up with a 280MB node-sass dependency in my node modules directory. This was a deal-breaker for me and so I ended up just copying your source.  Would it not be better to preprocess the scss to CSS before publishing?

**Comment by TheDiehard22** [comment]
In my opinion, that would be better.
We're working with less, so we don't want a node-sass dependency just for this component.

However it stills throws errors when adding node-sass to my node_modules.

**Comment by drewjbartlett** [comment]
Sorry I'm just getting to this. Right now I have the css/sass compiling with the vue component. I could include a compiled version of the sass and remove it from the component if someone wants to make a PR for this.

**Comment by CaiWenlie** [comment]
should use normal css instead of sass

**Comment by drewjbartlett** [comment]
@CaiWenlie What makes you say that? Using sass makes theming this a breeze.

**Comment by drewjbartlett** [comment]
@CaiWenlie @sellomkantjwa closing this out. v2 no longer uses sass as a dependency. It's a dev dependency and it compiles at publish and the component now includes a .css file instead :D
