### ISSUE TITLE
Using vue-switches with nuxt ssr.

### ISSUE THREAD

**Issue by danielverejan** [drewjbartlett/vue-switches#9]
Is it possible to use vue-switches with nuxt and ssr?
When included I get this error
![capture](https://user-images.githubusercontent.com/7072732/29362916-7a534e78-8296-11e7-9109-af922e769aa3.PNG)

**Comment by drewjbartlett** [comment]
You definitely can! This isn't a vue-switches problem but rather an implementation problem. See this comment: https://github.com/nuxt/nuxt.js/issues/1536#issuecomment-326266242

Essentially do this;

#### Step 1
Create `plugins/vue-switches.js` (in your nuxt directory) and add the following to it:

```js
import Vue from 'vue';
import Switches from 'vue-switches';

Vue.component('switches', Switches); 
```

#### Step 2
In `nuxt.config.js` add:

```js
plugins: [
   { src: '~/plugins/vue-switches', ssr: false }
]
```

Now you can use the component like:

```html
<switches v-model="selected"></switches>
```
